### ISSUE TITLE
errors in the configuration of this machine..

### ISSUE THREAD

**Issue by gitgianlu** [phretor/memory-errors-lab#1]
memory-errors-lab/linux32$ vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The box 'skrepo/debian_stable_32bit' could not be found.

**Comment by phretor** [comment]
Could you paste more verbose output?

It looks like a connectivity problem at a first glance ;)

**Comment by dsteb** [comment]
With polimi internet vagrant up processed about 1hr, but finished without errors and all seems  to work.

**Comment by gitgianlu** [comment]
It looks like the Ubuntu 14.4 version of Vagrant is too old..
Sorry I always try to stick on the current repository if possible ;-)
Cheers!

**Comment by dsteb** [comment]
With Ubuntu 14.04 x64 it is all working, just download last version deb from vagrant site.

**Comment by gitgianlu** [comment]
Ok thanks!
