### ISSUE TITLE
Inability to run the virtual machine properly: Connection timeout on boot

### ISSUE THREAD

**Issue by thedeste** [phretor/memory-errors-lab#3]
After having installed Virtual Box 4.3.10r93012 and Vagrant 1.5.4_i686 on my laptop running Crunchbang 11 Waldorf (based on Debian Wheezy) and trying to run vagrant, I get the following output:

memory-errors-lab/linux32$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'skrepo/debian_stable_32bit' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...

The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
# 

Is that a problem of the configuration of the virtual machine or a problem in my network configuration?

**Comment by stajfar** [comment]
Thedeste, did you find any solution to this issue? I have the same problem.

**Comment by phretor** [comment]
As suggested by the error message, have you tried the following?

"If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run vagrant up while the
VirtualBox GUI is open."

-F

**Comment by stajfar** [comment]
At "Vm settings -->Processor Tab",  I checked the "Enable PAE/NX" which was not enabled by default and it worked for me.

**Comment by phretor** [comment]
Closing this as seems related to the VM software.
